import { describe, expect, it } from 'vitest';
// @ts-expect-error Static search helpers are intentionally Node.js ESM scripts.
import { canonicalizeZBSearchDatabase } from '../scripts/canonicalize-zbsearch.mjs';

describe('static search determinism', () => {
  it('removes autogenerated external document-id entropy without touching search data', () => {
    const shared = {
      type: 'simple',
      language: 'multilingual',
      index: { searchableProperties: ['title', 'content'] },
      docs: { docs: { 1: { title: 'A', url: '/docs/a' }, 2: { title: 'B', url: '/docs/b' } } },
      sorting: { enabled: true },
      pinning: {},
    };

    const first = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25775151-0', '25775151-1'],
      },
    });
    const second = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25799174-0', '25799174-1'],
      },
    });

    const canonicalFirst = canonicalizeZBSearchDatabase(first);
    const canonicalSecond = canonicalizeZBSearchDatabase(second);

    expect(canonicalFirst).toBe(canonicalSecond);
    const parsed = JSON.parse(canonicalFirst);
    expect(parsed.internalDocumentIDStore.internalIdToId).toEqual([
      'static-search-1',
      'static-search-2',
    ]);
    expect(parsed.docs).toEqual(shared.docs);
    expect(parsed.index).toEqual(shared.index);
  });
});
