import { describe, expect, it } from 'vitest';
import { initSimpleSearch } from 'fumadocs-core/search/server';
import { staticClient } from 'fumadocs-core/search/client/orama-static';
// @ts-expect-error Static search helpers are intentionally Node.js ESM scripts.
import { canonicalizeZBSearchDatabase } from '../scripts/canonicalize-zbsearch.mjs';

describe('static search determinism', () => {
  it('loads canonicalized real exports with the browser client and preserves results', async () => {
    // https://www.fumadocs.dev/docs/headless/search/orama#static-export
    const server = initSimpleSearch({ indexes: [
      { title: 'Binary tree', content: 'Binary tree traversal algorithms', url: '/docs/tree' },
      { title: 'Matrix', content: 'Matrix multiplication', url: '/docs/matrix' },
    ] });
    const original = JSON.stringify(await server.export());
    const canonical = canonicalizeZBSearchDatabase(original);
    const from = (json: string) => `data:application/json,${encodeURIComponent(json)}`;
    const before = await staticClient({ from: from(original) }).search('binary');
    const after = await staticClient({ from: from(canonical) }).search('binary');
    expect(after).toEqual(before);
    expect(after.some((result) => result.url === '/docs/tree')).toBe(true);
  });

  it('removes autogenerated external document-id entropy without touching search data', () => {
    const shared = {
      type: 'simple',
      language: 'multilingual',
      index: { searchableProperties: ['title', 'content'] },
      docs: { docs: { 1: { title: 'A', url: '/docs/a' }, 2: { title: 'B', url: '/docs/b' } } },
      sorting: { enabled: true },
      pinning: {},
    };

    const first = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25775151-0', '25775151-1'],
      },
    });
    const second = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25799174-0', '25799174-1'],
      },
    });

    const canonicalFirst = canonicalizeZBSearchDatabase(first);
    const canonicalSecond = canonicalizeZBSearchDatabase(second);

    expect(canonicalFirst).toBe(canonicalSecond);
    const parsed = JSON.parse(canonicalFirst);
    expect(parsed.internalDocumentIDStore.internalIdToId).toEqual([
      'static-search-1',
      'static-search-2',
    ]);
    expect(parsed.docs).toEqual(shared.docs);
    expect(parsed.index).toEqual(shared.index);
  });
});
